# Generated by Django 4.1.3 on 2022-12-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="user",
        ),
    ]
